###-----------------------------------------------------------------------------
##  This file is part of
### ---              Timothy Budd's Kamin Interpreters in C++
###-----------------------------------------------------------------------------
### Title: General make configuration file
###-----------------------------------------------------------------------------

###-----------------------------------------------------------------------------
### Identification and inclusion of the default build environment
###-----------------------------------------------------------------------------
ifndef BUILDENV
   BUILDENV=$(BUILDENV_$(shell uname -s))
   BUILDENV_Linux=linux
endif

#include $(PROJECT_DIR)/Make/Makefile.config.$(BUILDENV)

###-----------------------------------------------------------------------------
### Set the default target
###-----------------------------------------------------------------------------
# TARGET = default | opt | debug
TARGET = default

###-----------------------------------------------------------------------------
### Set directories and general macros
###-----------------------------------------------------------------------------
ifndef DIR
    # The cd ./ in FULLDIR is for a corner case where . is a symbolic link
    # At least with bash (not sure with other shells), pwd returns me
    # the symbolic link path (as for BASEDIR), rather than the physical path
    # So this is necessary for the substitution to happen correctly. Ugh!
    BASEDIR=    $(shell cd ./$(PW_DIR); pwd)
    FULLDIR=	$(shell cd ./; pwd)
    DIR=        $(subst $(BASEDIR),,$(FULLDIR))
endif

OBJROOT=        $(PROJECT_DIR)/platforms/$(BUILDENV)/$(TARGET)
OBJDIR=		$(OBJROOT)$(DIR)
OBJECTS=	$(SOURCES:%.C=$(OBJDIR)/%.o)

###-----------------------------------------------------------------------------
